service: goosetunetv-view-counts-update
provider:
  name: aws
  runtime: ruby2.5
  region: ap-northeast-1
  iamRoleStatements:

functions:
  app:
    handler: app.lambda_handler
    events:
      - schedule: rate(60 minutes)
